authEnabled = false

[SwitcherConfig]
enabled=true
addr=":9854"

[ConsoleConfig]
enabled=true
addr=":9800"

[Auth."root"]
password="123456"
permits="*:*"

[DatabaseConfig]
endpoint="file:///$HOME/sparrow/"